const {test,expect}=require('@playwright/test');
const questions=Array.from({length:351},(_,i)=>({entry_id:'q'+i,question_id:'q'+i,code:'CODE-'+String(i).padStart(3,'0'),topic:'Algebra',skill:'Linear equations',stem:'Synthetic question '+i,type:'mcq',difficulty:'medium',ready:i!==0,unclassified:false,review_status:i===0?'review':'source_checked',hold_reason:i===0?'Ambiguous source':'',priority:i===0?1:3,published_uses:0,verified_release:'fixture'}));
async function setup(page,context){
 const calls=[],reads=[],errors=[],unexpected=[];let fail=false;
 page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.origin==='http://127.0.0.1:4173')return route.continue();
  if(url.href==='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.45.0/dist/umd/supabase.js')return route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient(){return {auth:{getSession:async()=>({data:{session:null}}),getUser:async()=>({data:{user:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async(name,args)=>{const r=await fetch('https://fixture.invalid/rpc',{method:'POST',body:JSON.stringify({name,args})});return r.json()},from(table){const filters=[];const q={select:()=>q,eq:(k,v)=>{filters.push([k,v]);return q},single:async()=>{const r=await fetch('https://fixture.invalid/detail',{method:'POST',body:JSON.stringify({table,filters})});return r.json()}};return q}}}};`});
  if(url.hostname==='fonts.googleapis.com'||(url.hostname==='cdn.jsdelivr.net'&&url.pathname.startsWith('/npm/katex@0.16.9/dist/')))return route.fulfill({body:'',contentType:route.request().resourceType()==='script'?'application/javascript':'text/css'});
  if(url.href==='https://fixture.invalid/rpc'){
   const body=JSON.parse(route.request().postData());calls.push(body);if(body.name!=='admin_bank_page'){unexpected.push(body.name);return route.abort();}
   if(fail){fail=false;return route.fulfill({json:{data:null,error:{message:'Offline fixture'}}});}
   const a=body.args;let rows=questions.filter(x=>(!a.p_search||[x.code,x.stem,x.question_id].join(' ').toLowerCase().includes(a.p_search.toLowerCase()))&&(!a.p_status||a.p_status==='ready'?(!a.p_status||x.ready):x.review_status===a.p_status));
   const reply={total:rows.length,page:a.p_page,size:50,items:rows.slice(a.p_page*50,(a.p_page+1)*50),lessons:['Algebra'],summary:{total:351,held:1,unclassified:0,independently_solved:0}};
   if(a.p_search==='slow')await new Promise(r=>setTimeout(r,600));
   return route.fulfill({json:{data:reply,error:null}});
  }
  if(url.href==='https://fixture.invalid/detail'){
   const body=JSON.parse(route.request().postData());reads.push(body);return route.fulfill({json:{data:body.table==='question_keys'?{question_id:body.filters[0][1],correct:'A',explanation:'Worked original'}:{id:body.filters[0][1],track_id:'est',topic:'Algebraic expressions and equations',type:'mcq',difficulty:'medium',stem:'Full original',choices:[{key:'A',text:'1'},{key:'B',text:'2'}],assets:{svg:'<svg aria-label="Original figure"></svg>',source_code:'CODE-001',lesson_subtopic:'Original skill',provenance:'Original metadata'}},error:null}});
  }
  unexpected.push(url.href);return route.abort();
 });
 await page.goto('/admin.html');await page.waitForFunction(()=>typeof pagedQuestionBank==='function');
 await page.evaluate(async()=>{ST.me={role:'instructor'};ST.tracks=[{id:'est',name:'EST I'}];ST.track='est';ST.view='bank';await render();show(true);});
 return {calls,reads,errors,unexpected,fail:()=>{fail=true;}};
}
test('all 351 bank questions are reachable, selection survives pages, held rows stay unselectable and assets load only on edit',async({page,context},testInfo)=>{
 const audit=await setup(page,context);await expect(page.locator('#bankCount')).toContainText('1–50 of 351');await expect(page.locator('#bankTable tbody tr')).toHaveCount(50);await expect(page.locator('[data-bank-select="q0"]')).toHaveCount(0);expect(audit.reads).toEqual([]);
 await page.locator('[data-bank-select="q1"]').check();for(let i=0;i<7;i++){await page.locator('#bankNext').click();await expect(page.locator('#bankPage')).toContainText('Page '+(i+2));}
 await expect(page.locator('#bankTable')).toContainText('CODE-350');await expect(page.locator('#bankNext')).toBeDisabled();await page.locator('[data-bank-select="q350"]').check();await expect(page.locator('#examFromBank')).toHaveText('Create exam (2)');
 await page.locator('#qSearch').fill('CODE-001');await expect(page.locator('#bankCount')).toContainText('1–1 of 1');await expect(page.locator('[data-bank-select="q1"]')).toBeChecked();await expect(page.locator('#examFromBank')).toHaveText('Create exam (2)');
 await page.evaluate(()=>{window.savedQuestion=null;mutation=async(action,data)=>{window.savedQuestion={action,data};};render=async()=>{};});await page.locator('[data-edit-q="q1"]').click();await expect(page.locator('#editor')).toBeVisible();await expect(page.locator('#qassets')).toContainText('Original figure');expect(audit.reads).toHaveLength(2);expect(audit.reads[0].filters).toEqual([['id','q1'],['track_id','est']]);await expect(page.locator('#qcorrect')).toHaveValue('A');await page.locator('#qskill').fill('Reviewed detailed skill');await page.locator('#qsourceCode').fill('REVIEWED-CODE');await page.locator('#editSave').click();await expect(page.locator('#editor')).not.toBeVisible();const saved=await page.evaluate(()=>savedQuestion);expect(saved.action).toBe('question.save');expect(saved.data.assets.svg).toContain('Original figure');expect(saved.data.assets.provenance).toBe('Original metadata');expect(saved.data.assets.lesson_subtopic).toBe('Reviewed detailed skill');expect(saved.data.assets.source_code).toBe('REVIEWED-CODE');expect(saved.data.correct).toBe('A');
 await page.locator('#bankClear').click();await expect(page.locator('#examFromBank')).toBeDisabled();await page.locator('#qSearch').fill('');await expect(page.locator('#bankCount')).toContainText('1–50 of 351');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#bankTable tbody tr').first().screenshot({path:testInfo.outputPath('bank-first-entry.png')});if(testInfo.project.name==='mobile'){const b=await page.locator('[data-edit-q]').first().boundingBox();expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(390);}await page.screenshot({path:testInfo.outputPath('paged-bank.png'),fullPage:false});expect(audit.errors).toEqual([]);expect(audit.unexpected).toEqual([]);
});
test('failed searches retry and stale responses cannot replace newer filters or another view',async({page,context})=>{
 const audit=await setup(page,context);audit.fail();await page.locator('#bankStatus').selectOption('review');await expect(page.locator('#bankError')).toContainText('Offline fixture');await page.locator('#bankRetry').click();await expect(page.locator('#bankCount')).toContainText('1–1 of 1');
 await page.locator('#bankStatus').selectOption('');await expect(page.locator('#bankCount')).toContainText('351');await page.locator('#qSearch').fill('slow');await expect.poll(()=>audit.calls.at(-1).args.p_search).toBe('slow');await page.locator('#qSearch').fill('CODE-350');await expect(page.locator('#bankTable')).toContainText('CODE-350');await page.waitForTimeout(650);await expect(page.locator('#bankTable')).toContainText('CODE-350');
 await page.locator('#qSearch').fill('slow');await expect.poll(()=>audit.calls.at(-1).args.p_search).toBe('slow');await page.evaluate(()=>{ST.view='overview';document.getElementById('view').innerHTML='<p id="newView">Other view</p>';});await page.waitForTimeout(650);await expect(page.locator('#newView')).toHaveText('Other view');await page.evaluate(async()=>{ST.view='bank';await bank();document.getElementById('qSearch').value='queued';document.getElementById('qSearch').oninput();ST.view='overview';document.getElementById('view').innerHTML='<p id="newView">Other view</p>';});await page.waitForTimeout(350);await expect(page.locator('#newView')).toHaveText('Other view');expect(audit.errors).toEqual([]);expect(audit.unexpected).toEqual([]);
});
