const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const context={ST:{track:{id:'est',theme:{label:'EST'}}},DASH:{mistakes:{items:[],remaining:0,mastered:0},mistakesLoading:false,mistakesError:'',notebookFeedback:{},drill:{drill_id:null,questions:[]}},esc:s=>String(s).replaceAll('<','&lt;'),figure:()=>'',setInterval:()=>{},document:{addEventListener:()=>{}},Date,console};
vm.createContext(context);
vm.runInContext(readFileSync('web/daily-challenge.js','utf8'),context);
const d={track:'est',completed:false,server_now:'2026-09-14T20:00:00Z',reset_at:'2026-09-14T21:00:00Z',receivedAt:1000,streak:{current:3,longest:14,week:[{date:'2026-09-14',completed:false,today:true}]}};
assert.equal(context.streakRemaining(d,1000).seconds,3600);
assert.equal(context.streakRemaining(d,61000).seconds,3540);
assert.equal(context.streakRemaining(d,3601001).seconds,0);
const html=context.streakPanel(d);
assert.match(html,/keep your 3-day streak/);
assert.match(html,/4 more consecutive days/);
assert.equal((html.match(/is-earned/g)||[]).length,3);
assert.match(html,/30 days <small>Locked/);
assert.match(html,/aria-label="2026-09-14: To do"/);
assert.match(context.streakPanel({...d,completed:true}),/Streak secured for today/);
assert.match(context.streakPanel({...d,streak:{...d.streak,current:0}}),/start your streak/);
assert.equal(context.streakPanel({...d,streak:null}),'');
assert.match(context.mistakesPanel(),/No mistakes to practise right now/);
context.DASH.mistakes={remaining:1,mastered:0,items:[{id:'q1',type:'mcq',streak:1,topic:'Algebra',stem:'Solve x &lt; 3',choices:[{key:'A',text:'1'},{key:'B',text:'4'}]}]};
const mistakes=context.mistakesPanel();
assert.match(mistakes,/Mistake notebook/);
assert.match(mistakes,/1\/2 correct in a row/);
assert.doesNotMatch(mistakes,/Correct answer:/);
assert.match(mistakes,/Solve x &lt; 3/);
assert.match(context.drillPanel(),/Build 15–18 questions/);
context.DASH.drill={drill_id:'d1',topics:['Algebra'],completed:false,questions:[{id:'q1',stem:'Solve',topic:'Algebra',type:'mcq',choices:[{key:'A',text:'2'}]}]};
assert.match(context.drillPanel(),/Submit drill/);
assert.doesNotMatch(context.drillPanel(),/Correct answer:/);
console.log('PASS: timer clock offset/expiry, active/completed/new streak, earned badges and accessible day labels');
