const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const context={ST:{track:{id:'est',theme:{label:'EST'}}},DASH:{mistakes:{items:[]},mistakesLoading:false,mistakesError:''},esc:s=>String(s).replaceAll('<','&lt;'),renderAssets:()=>'',setInterval:()=>{},document:{addEventListener:()=>{}},Date,console};
vm.createContext(context);
vm.runInContext(readFileSync('web/daily-challenge.js','utf8'),context);
const d={track:'est',completed:false,server_now:'2026-09-14T20:00:00Z',reset_at:'2026-09-14T21:00:00Z',receivedAt:1000,streak:{current:3,longest:14,week:[{date:'2026-09-14',completed:false,today:true}]}};
assert.equal(context.streakRemaining(d,1000).seconds,3600);
assert.equal(context.streakRemaining(d,61000).seconds,3540);
assert.equal(context.streakRemaining(d,3601001).seconds,0);
const html=context.streakPanel(d);
assert.match(html,/keep your 3-day streak/);
assert.match(html,/4 more consecutive days/);
assert.equal((html.match(/is-earned/g)||[]).length,3);
assert.match(html,/30 days <small>Locked/);
assert.match(html,/aria-label="2026-09-14: To do"/);
assert.match(context.streakPanel({...d,completed:true}),/Streak secured for today/);
assert.match(context.streakPanel({...d,streak:{...d.streak,current:0}}),/start your streak/);
assert.equal(context.streakPanel({...d,streak:null}),'');
assert.match(context.mistakesPanel(),/No wrong quiz answers yet/);
context.DASH.mistakes={items:[{date:'2026-09-14',topic:'Algebra',stem:'Solve x &lt; 3',choices:[{key:'A',text:'1'},{key:'B',text:'4'}],submitted:'B',correct:'A',explanation:'Substitute each choice.'}]};
const mistakes=context.mistakesPanel();
assert.match(mistakes,/Wrong answers/);
assert.match(mistakes,/Your answer/);
assert.match(mistakes,/Correct/);
assert.match(mistakes,/Solve x &lt; 3/);
console.log('PASS: timer clock offset/expiry, active/completed/new streak, earned badges and accessible day labels');
