begin;
set local role service_role;
do $$
declare u uuid; other_ uuid; staff_ uuid; ex uuid; attempt_ uuid; request_ uuid:=gen_random_uuid(); r jsonb; payload jsonb; saved_ jsonb;
begin
 select id into u from public.profiles where role='student' and status='active' limit 1;
 select id into other_ from public.profiles where role='student' and status='active' and id<>u limit 1;
 select id into staff_ from public.profiles where role='admin' and status='active' limit 1;
 assert u is not null and other_ is not null and staff_ is not null,'fixtures required';
 insert into public.tracks(id,name) values('activity_test','Disposable exam activity test');
 insert into public.enrollments(user_id,track_id) values(u,'activity_test');
 insert into public.exams(track_id,title,duration_seconds,assessment_type) values('activity_test','Disposable timed exam',600,'full_exam') returning id into ex;
 insert into public.attempts(user_id,exam_id,attempt_no,shuffle_seed,deadline_at,total) values(u,ex,1,1,now()+interval '10 minutes',10) returning id into attempt_;
 select to_jsonb(a) into saved_ from public.attempts a where id=attempt_;
 payload:=jsonb_build_object('attempt_id',attempt_,'events',jsonb_build_array(jsonb_build_object('id',request_,'kind','hidden','at',now())));
 r:=public.exam_activity(u,'events',payload);assert r->'accepted'=jsonb_build_array(request_),'event acknowledged';
 assert public.exam_activity(u,'events',payload)=r,'retry response';
 assert (select count(*) from public.exam_activity_events where attempt_id=attempt_)=1,'retry duplicated';
 assert saved_=(select to_jsonb(a) from public.attempts a where id=attempt_),'activity altered attempt or marks';
 begin perform public.exam_activity(other_,'events',payload);raise exception 'other student write bypass';exception when others then if sqlerrm<>'attempt_not_found' then raise;end if;end;
 begin perform public.exam_activity(u,'summary','{"track":"activity_test"}');raise exception 'student read bypass';exception when others then if sqlerrm<>'staff_required' then raise;end if;end;
 r:=public.exam_activity(staff_,'summary','{"track":"activity_test"}');assert (r->'items'->0->>'departures')::int=1,'summary departures';
 r:=public.exam_activity(staff_,'details',jsonb_build_object('attempt_id',attempt_));assert jsonb_array_length(r->'events')=1,'details';
 update public.profiles set role='instructor' where id=other_;
 begin perform public.exam_activity(other_,'summary','{"track":"activity_test"}');raise exception 'instructor track bypass';exception when others then if sqlerrm<>'forbidden_track' then raise;end if;end;
 insert into public.instructor_tracks(user_id,track_id) values(other_,'activity_test');
 assert jsonb_array_length(public.exam_activity(other_,'summary','{"track":"activity_test"}')->'items')=0,'unassigned student exposed';
 begin perform public.exam_activity(other_,'details',jsonb_build_object('attempt_id',attempt_));raise exception 'instructor details bypass';exception when others then if sqlerrm<>'attempt_not_found' then raise;end if;end;
 insert into public.groups(track_id,name,instructor_id) values('activity_test','Disposable group',other_) returning id into request_;
 insert into public.group_members(group_id,user_id) values(request_,u);
 assert jsonb_array_length(public.exam_activity(other_,'summary','{"track":"activity_test"}')->'items')=1,'assigned student missing';
 payload:=jsonb_build_object('attempt_id',attempt_,'events',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'kind','hidden','at',now()+interval '1 day')));
 begin perform public.exam_activity(u,'events',payload);raise exception 'future time accepted';exception when others then if sqlerrm<>'invalid_event' then raise;end if;end;
 update public.exams set assessment_type='lesson_exam' where id=ex;
 begin perform public.exam_activity(u,'events',payload);raise exception 'lesson tracked';exception when others then if sqlerrm<>'activity_not_enabled' then raise;end if;end;
 assert not has_table_privilege('authenticated','public.exam_activity_events','select'),'activity exposed';
 assert not has_function_privilege('authenticated','public.exam_activity(uuid,text,jsonb)','execute'),'actor spoofing';
end $$;
rollback;
