// Disposable PostgreSQL only; synthetic unchanged questions do not certify their mathematics.
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict'),db=new PGlite();
const dir='content-releases/20261005_remaining_skill_review/',read=p=>fs.readFileSync(p,'utf8'),load=n=>JSON.parse(read(dir+n+'.json'));
const scalar=async(s,a=[])=>Object.values((await db.query(s,a)).rows[0])[0];
async function main(){
 const data=load('packet'),actual=load('defect-fixtures'),id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
 for(const f of ['tests/00_shim.sql','supabase/migrations/001_schema.sql'])await db.exec(read(f).replace(/create extension if not exists pgcrypto;/g,''));
 await db.exec("alter table exams add column is_full_length boolean default false,add column assessment_type text default 'lesson_exam',add column scoring_map jsonb,add column exam_set_code text,add column module_number int,add column module_count int;create table revision_items(question_id uuid primary key,idea text,focus jsonb,active boolean,lesson text,difficulty text,programmes text[],fingerprint text);insert into tracks(id,name) values('est','EST I');");
 const put=async q=>{await db.query('insert into questions(id,track_id,topic,difficulty,type,stem,choices,assets) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb)',[q.id,q.track_id,q.topic,q.difficulty||'medium',q.type||'mcq',q.stem,JSON.stringify(q.choices),JSON.stringify(q.assets)]);await db.query('insert into question_keys values($1,$2::jsonb,$3)',[q.id,JSON.stringify(q.correct),q.explanation]);};
 for(const d of data.decisions){const a=actual.find(q=>q.id===d.id);await put({...a,id:d.id,track_id:'est',topic:d.before_topic,stem:a?.stem||'Synthetic unchanged question',choices:a?.choices||[{key:'A',text:'1'},{key:'B',text:'2'}],correct:a?.correct||'A',explanation:a?.explanation||'Synthetic unchanged solution',assets:{lesson_subtopic:'Needs classification',source_code:d.source,source_metadata:'Preserve me',image:'https://fixture.invalid/original.png',...(d.prior_held?{release_hold_reason:'Existing hold'}:{})}});}
 const weighted=JSON.parse(read('content-releases/20261005_reviewed_exam_versions/adaptations.json')).find(q=>q.code==='weighted-mean');await put(weighted);
 await db.query('insert into auth.users(id) values($1)',[id(1)]);await db.query("insert into profiles(id,role) values($1,'student')",[id(1)]);
 for(const g of data.guards.exams){await db.query('insert into exams select (jsonb_populate_record(null::public.exams,$1::jsonb)).*',[JSON.stringify(g.exam)]);await db.query('insert into assignments(exam_id,user_id) values($1,$2)',[g.exam.id,id(1)]);}
 // Valid unrelated history must survive this release byte-for-byte.
 await db.query("insert into exams(id,track_id,title,duration_seconds,question_ids) values($1,'est','Unrelated',600,$2::uuid[])",[id(2),[data.decisions[0].id]]);await db.query("insert into attempts(id,user_id,exam_id,attempt_no,shuffle_seed,deadline_at,status,score,total) values($1,$2,$3,1,1,now(),'graded',1,1)",[id(3),id(1),id(2)]);
 await db.exec(read('supabase/sql/question_eligibility_core.sql'));
 const support=read('tests/fixtures/oct4-support-functions.sql');await db.exec(support.match(/CREATE OR REPLACE FUNCTION public.revision_question_fingerprint[\s\S]*?\$function\$;/i)[0]);
 for(const r of data.guards.revisions){await db.query('insert into revision_items select (jsonb_populate_record(null::revision_items,$1::jsonb)).*',[JSON.stringify(r.row)]);await db.query('update revision_items r set fingerprint=public.revision_question_fingerprint(q.stem,q.choices,q.assets,k.correct,k.explanation) from questions q join question_keys k on k.question_id=q.id where q.id=r.question_id');r.hash=await scalar('select md5(to_jsonb(r)::text) from revision_items r where question_id=$1',[r.id]);}
 for(const d of data.decisions)d.hash=await scalar("select md5(jsonb_build_object('q',to_jsonb(q),'k',to_jsonb(k))::text) from questions q join question_keys k on k.question_id=q.id where q.id=$1",[d.id]);
 for(const g of data.guards.exams){g.hash=await scalar('select md5(to_jsonb(e)::text) from exams e where id=$1',[g.exam.id]);g.assignment_hash=await scalar("select md5(coalesce(jsonb_agg(to_jsonb(a) order by id),'[]'::jsonb)::text) from assignments a where exam_id=$1",[g.exam.id]);}
 data.guards.weighted_hash=await scalar("select md5(jsonb_build_object('q',to_jsonb(q),'k',to_jsonb(k))::text) from questions q join question_keys k on k.question_id=q.id where q.id=$1",[weighted.id]);
 const beforeQ=(await db.query('select * from questions order by id')).rows,keys=(await db.query('select * from question_keys order by question_id')).rows,exams=(await db.query('select * from exams order by id')).rows,assignments=(await db.query('select * from assignments order by id')).rows,history=(await db.query('select * from attempts')).rows,revision=(await db.query('select * from revision_items')).rows;
 let sql=read(dir+'apply.sql');sql=sql.replace(/data_ jsonb:='(?:[^']|'')*'::jsonb;/,"data_ jsonb:='"+JSON.stringify(data).replaceAll("'","''")+"'::jsonb;");
 await db.query('update questions set stem=stem||$2 where id=$1',[data.decisions.at(-1).id,' late edit']);await assert.rejects(()=>db.exec(sql),/Concurrent question change/);await db.exec('rollback');assert.equal(await scalar("select to_regclass('portal_private.skill_review_20261005_backup')"),null);await db.query('update questions set stem=$2 where id=$1',[data.decisions.at(-1).id,beforeQ.find(q=>q.id===data.decisions.at(-1).id).stem]);
 await db.query('insert into attempts(user_id,exam_id,attempt_no,shuffle_seed,deadline_at,status) values($1,$2,1,1,now(),$3)',[id(1),data.guards.exams[0].exam.id,'graded']);await assert.rejects(()=>db.exec(sql),/student history/);await db.exec('rollback');await db.query('delete from attempts where exam_id=$1',[data.guards.exams[0].exam.id]);
 await db.exec(sql);
 for(const d of data.decisions){const after=(await db.query('select * from questions where id=$1',[d.id])).rows[0],before=beforeQ.find(q=>q.id===d.id);assert.equal(after.topic,d.topic);assert.equal(after.assets.lesson_subtopic,d.skill);assert.equal(after.assets.image,before.assets.image);assert.equal(after.assets.source_metadata,before.assets.source_metadata);assert.deepEqual({...after,topic:before.topic,assets:before.assets},before);if(d.prior_held)assert.equal(after.assets.release_hold_reason,'Existing hold');}
 assert.equal(await scalar("select count(*)::int from questions where assets->>'lesson_subtopic'='Needs classification'"),0);
 const afterKeys=(await db.query('select * from question_keys where question_id<>$1 order by question_id',[data.adaptation.id])).rows;assert.deepEqual(afterKeys,keys);assert.deepEqual((await db.query('select * from assignments order by id')).rows,assignments);assert.deepEqual((await db.query('select * from attempts')).rows,history);assert.deepEqual((await db.query('select * from revision_items')).rows,revision);
 for(const c of data.changes){const after=(await db.query('select * from exams where id=$1',[c.id])).rows[0],before=exams.find(e=>e.id===c.id);assert.deepEqual({...after,title:before.title,question_ids:before.question_ids},before);assert.equal(after.question_ids.length,before.question_ids.length);assert.equal(await scalar('select portal_private.exam_content_ready(question_ids,track_id) from exams where id=$1',[c.id]),true);}
 assert.equal(await scalar("select count(*)::int from questions where id in(select key::uuid from jsonb_each_text($1::jsonb)) and assets->>'release_hold_reason' is not null",[JSON.stringify(data.holds)]),4);assert.equal(await scalar("select has_table_privilege('authenticated','portal_private.skill_review_20261005_backup','select')"),false);assert.equal(await scalar("select has_table_privilege('anon','portal_private.skill_review_20261005_backup','select')"),false);
 await assert.rejects(()=>db.exec(sql),/already exists/);await db.exec('rollback');
 const rollback=read(dir+'rollback.sql');await db.query('update questions set stem=stem||$2 where id=$1',[data.adaptation.id,' later edit']);await assert.rejects(()=>db.exec(rollback),/Concurrent question\/key edit/);await db.exec('rollback');await db.query('update questions set stem=$2 where id=$1',[data.adaptation.id,data.adaptation.stem]);await db.exec(rollback);
 for(const d of data.decisions){const q=(await db.query('select * from questions where id=$1',[d.id])).rows[0],before=beforeQ.find(q=>q.id===d.id);assert.equal(q.topic,before.topic);assert.equal(q.assets.lesson_subtopic,'Needs classification');if(data.holds[d.id])assert.equal(q.assets.release_hold_reason,data.holds[d.id]);}
 for(const c of data.changes){const q=(await db.query('select * from exams where id=$1',[c.id])).rows[0];assert.equal(q.title,exams.find(e=>e.id===c.id).title);assert.deepEqual(q.question_ids,c.question_ids);assert.equal(await scalar('select portal_private.exam_content_ready(question_ids,track_id) from exams where id=$1',[c.id]),true);}
 assert.deepEqual((await db.query('select * from question_keys where question_id<>$1 order by question_id',[data.adaptation.id])).rows,keys);assert.deepEqual((await db.query('select * from attempts')).rows,history);
 console.log('PASS: 146 classifications, 19 lessons, four preserved source holds, five ready exams; original keys, images, source metadata, timers, assignments, history and revision fingerprints preserved; concurrency/history/replay guards and private backup; metadata rollback retains holds and verified replacements.');await db.close();
}main().catch(async e=>{console.error(e);await db.close();process.exitCode=1;});
