DO $review$ DECLARE v jsonb; b public.question_bank%rowtype; BEGIN
FOR v IN SELECT value FROM jsonb_array_elements($payload$[{"id": "college_panda_10_practice_tests-test01-s3-q16", "before_stem": "If |1 − x| > 4 and x is positive, what is one possible value of x?", "explanation": "|1 − x| > 4 gives x < −3 or x > 5. Since x is positive, every real x > 5 is valid.", "note": "Rechecked algebra. Retain release hold: the grader must accept the full open range x > 5, not one sample response."}, {"id": "college_panda_10_practice_tests-test01-s4-q33", "before_stem": "For g(x) = √[(x − 1)(x − 2)], what is one possible value of x for which g is undefined over the real numbers?", "explanation": "Over the real numbers the square root is undefined when (x − 1)(x − 2) < 0, exactly when 1 < x < 2. Endpoints are defined.", "note": "Rechecked sign intervals and endpoints. Retain release hold: numeric interval grading is required."}, {"id": "est1_dec_2025-q00019", "before_stem": "20. If 4x 2 12x 52 is written as 4(x n)2 m, what is the value of (m n)?", "explanation": "Completing the square gives 4x² − 12x + 52 = 4(x − 3/2)² + 43. If the intended form were 4(x − n)² + m, mn would be 129/2. The printed form instead says 4(x − n)² = m; that does not define such an identity.", "note": "Original page 6 visually rechecked. The source equation is defective; do not silently replace its equality sign by a plus sign."}, {"id": "est2_hs_level1_jan_2026-q00054", "before_stem": "Given 4x² + 8xz + 4y² − 4y = 110, find 4r³ if x = y = z = r.", "explanation": "Putting x = y = z = r gives 16r² − 4r − 110 = 0, or (4r − 11)(2r + 5) = 0. Thus r = 11/4 or −5/2 and 4r³ is 83.1875 or −62.5. Neither exact value is listed, and positivity is not specified.", "note": "Original page 27 visually rechecked. Retain hold: two admissible values and no exact printed answer."}, {"id": "statistics_probability_hw_aug_2026-q00006", "before_stem": "Q6. Three people: 160, 170, 180 cm. One leaves, another joins. New mean = 175. New\n person's height?", "explanation": "The old total is 160 + 170 + 180 = 510 cm, and the new total is 3 × 175 = 525 cm. If the departing height is d and the newcomer has height h, then 510 − d + h = 525, so h = d + 15. The possible heights are 175, 185, and 195 cm.", "note": "Original page 3 visually rechecked. Retain hold: the departing person is not identified; a single listed plausible value does not make the question determinate."}]$payload$::jsonb) LOOP
 IF EXISTS(SELECT 1 FROM public.audit_log WHERE action='staged_blocker_recheck_20260929' AND target_id=v->>'id') THEN CONTINUE;END IF;
 SELECT * INTO b FROM public.question_bank WHERE question_id=v->>'id' FOR UPDATE;
 IF b.question_id IS NULL OR b.publication_status<>'review_required' OR NOT b.needs_review OR b.stem_text IS DISTINCT FROM v->>'before_stem' THEN RAISE EXCEPTION 'Staged blocker changed %',v->>'id';END IF;
 INSERT INTO public.audit_log(action,target_type,target_id,meta) VALUES('staged_blocker_recheck_20260929','question_bank',b.question_id,jsonb_build_object('before',to_jsonb(b),'review',v-'before_stem'));
 UPDATE public.question_bank SET answer_explanation=v->>'explanation',answer_key_status='rechecked_blocked_20260929',review_reasons=coalesce(review_reasons,'[]'::jsonb)||jsonb_build_array('Rechecked 2026-09-29: '||(v->>'note')) WHERE question_id=b.question_id;
END LOOP; END;$review$;
SELECT count(*) rechecked_blockers FROM public.audit_log WHERE action='staged_blocker_recheck_20260929';
