"""Generate guarded data-only SQL from the reviewed repair manifest (offline)."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parent
payload=json.dumps(sorted(json.loads((ROOT/'repairs.json').read_text()),key=lambda r:r['id']),ensure_ascii=False,separators=(',',':'))
sql='''-- June remaining-record review. No schema, membership, track or result changes.
-- Generated by build_sql.py. Exact content and asset guards; atomic and replay-safe.
begin;
do $review$
declare
  item jsonb;
  q public.questions%rowtype;
  k public.question_keys%rowtype;
  previous public.audit_log%rowtype;
  next_assets jsonb;
  changed integer:=0;
begin
  for item in select value from jsonb_array_elements($payload$PAYLOAD$payload$::jsonb) loop
    select * into strict q from public.questions where id=(item->>'id')::uuid for update;
    select * into strict k from public.question_keys where question_id=q.id for update;
    select * into previous from public.audit_log
      where action='question_content_review' and target_id=q.id::text
      and meta->>'batch'='20260929-june-remaining-356' limit 1;
    if found then
      if q.track_id is distinct from item->>'track_id'
         or jsonb_build_object('stem',q.stem,'choices',q.choices,'correct',k.correct,'explanation',k.explanation) is distinct from item->'after'
         or q.assets is distinct from previous.meta->'after_assets' then
        raise exception 'Reviewed record changed after application: %',q.id;
      end if;
      continue;
    end if;
    if q.track_id is distinct from item->>'track_id'
       or md5(q.assets::text) is distinct from item->>'before_assets_md5'
       or jsonb_build_object('stem',q.stem,'choices',q.choices,'correct',k.correct,'explanation',k.explanation) is distinct from item->'before' then
      raise exception 'Concurrent content or asset change: %',q.id;
    end if;
    next_assets=q.assets || (item->'asset_patch');
    if q.assets ? 'release_hold_reason' and next_assets->>'release_hold_reason' is distinct from q.assets->>'release_hold_reason' then
      raise exception 'Existing hold must be preserved: %',q.id;
    end if;
    if item->>'status'='held' then
      if item#>'{after,correct,void}' is distinct from 'true'::jsonb
         or coalesce(next_assets->>'release_hold_reason','')='' then
        raise exception 'Held record must have void key and reason: %',q.id;
      end if;
    elsif not exists(select 1 from jsonb_array_elements(item#>'{after,choices}') c where c->>'key'=item#>>'{after,correct}') then
      raise exception 'Missing answer choice: %',q.id;
    end if;
    insert into public.audit_log(action,target_type,target_id,meta)
      values('question_content_review','question',q.id::text,jsonb_build_object(
      'batch','20260929-june-remaining-356','before',item->'before','after',item->'after',
      'before_assets',q.assets,'after_assets',next_assets,'reasons',item->'reasons',
      'source_page',item->'source_page','source_question',item->'source_question'));
    if q.stem is distinct from item#>>'{after,stem}' or q.choices is distinct from item#>'{after,choices}' or q.assets is distinct from next_assets then
      update public.questions set stem=item#>>'{after,stem}',choices=item#>'{after,choices}',assets=next_assets where id=q.id;
    end if;
    update public.question_keys set correct=item#>'{after,correct}',explanation=item#>>'{after,explanation}' where question_id=q.id;
    changed:=changed+1;
  end loop;
  raise notice 'Applied % June remaining-record repairs',changed;
end $review$;
commit;
'''.replace('PAYLOAD',payload)
(ROOT/'apply.sql').write_text(sql)
