begin;
set local lock_timeout='5s';
lock table questions,question_keys,revision_items in share row exclusive mode;
create temporary table est_reconcile on commit drop as select * from jsonb_to_recordset('[{"id":"4e5d0e24-836e-5e18-85af-6868807dc27e","q_digest":"d08d618deb8bd8d28b738b39cb9ef270","key_digest":"7adfd1fae398ba6586610a1ac49cbf9a","proof":"Count multiples independently:25 even +10 multiples of5 −5 multiples of10=30. Uniform probability30/50=0.6; half0.3, D.","image":null},{"id":"afee4921-ee14-551e-abe7-c86f4f3acb45","q_digest":"f577490a3244cda0b0c4fb846f91f6ee","key_digest":"303278e8aca81b011fcafbe6af121117","proof":"Original crop checked. Divide −3x/2≥−2 reverses inequality: x≤4/3. Increasing target9x/8+1 attainsmaximum2.5 at4/3; A. Preserve original revision hard and Unique metadata.","image":"https://math.portal.ghoneem.com/exams/est-september-2026/clean-hoa-007.png"},{"id":"b515a6ed-1c6f-5848-b2b4-12c02a5d4524","q_digest":"38be0926b33206d22970b2f68164e556","key_digest":"88da4a849618c26982abe635cb2e8ce5","proof":"Original graph checked:vertex(1,0),points(0,−1),(2,−1); y=−(x−1)². I andIII true,II false; D. Restore one representative only; tangent companion staysinactive.","image":"https://math.portal.ghoneem.com/exams/est-banks-2026/figures/aaf-048-1.png"}]'::jsonb) as t(id uuid,q_digest text,key_digest text,proof text,image text);
do $$ begin
if exists(select 1 from audit_log where action='revision.est_prune_reviewed_reconciliation.20260930') then raise exception 'Reconciliation already applied';end if;
if (select count(*) from est_reconcile t join questions q on q.id=t.id join question_keys k on k.question_id=q.id join revision_items r on r.question_id=q.id where q.track_id='est' and md5(to_jsonb(q)::text)=t.q_digest and md5(to_jsonb(k)::text)=t.key_digest and nullif(q.assets->>'release_hold_reason','') is null and coalesce((q.assets->>'bank_removed')::boolean,false)=false and not r.active)<>3 then raise exception 'Reconciliation source version changed or held';end if;
if exists(select 1 from est_reconcile t join revision_items r on r.question_id=t.id join revision_items a on a.lesson=r.lesson and lower(trim(a.idea))=lower(trim(r.idea)) and a.difficulty=r.difficulty join questions q on q.id=a.question_id where a.active and q.track_id='est') then raise exception 'An existing EST representative must not be replaced';end if;
end $$;
insert into audit_log(action,target_type,target_id,meta) select 'revision.est_prune_reviewed_reconciliation.20260930','question',q.id::text,jsonb_build_object('previous_assets',q.assets,'previous_revision',to_jsonb(r),'proof',t.proof,'scope','New independent verification of exact corrected current source; deliberate certificate reconciliation, not automatic stale refresh') from est_reconcile t join questions q on q.id=t.id join revision_items r on r.question_id=q.id;
update questions q set assets=q.assets||jsonb_build_object('answer_review','2026-09-30-independent-prune-source-reconciliation','mathematical_review_scope',t.proof)||case when t.image is not null then jsonb_build_object('image',t.image) else '{}'::jsonb end from est_reconcile t where q.id=t.id;
update revision_items r set active=true,fingerprint=revision_question_fingerprint(q.stem,q.choices,q.assets,k.correct,k.explanation) from est_reconcile t join questions q on q.id=t.id join question_keys k on k.question_id=q.id where r.question_id=q.id;
do $$ begin
if exists(select 1 from revision_items r join questions q on q.id=r.question_id where r.active and q.track_id='est' group by q.track_id,r.lesson,lower(trim(r.idea)),r.difficulty having count(*)>2) then raise exception 'Representative cap violated';end if;
end $$;
commit;
