// Metadata pages only; diagrams, tables and editable originals load on demand.
const BANK_REVIEW_LABELS={review:'Held / needs content review',pending:'Math review pending',source_checked:'Release checked · math review pending',independently_solved:'Independently solved'};
async function pagedQuestionBank(){
 if(!ST.track){$('view').innerHTML='<div class="msg">Choose a track at the top to browse its question bank.</div>';return;}
 const track=ST.track,chosen=new Set();let page=0,request=0,timer;
 $('view').innerHTML=`<div class="head"><h2>Question bank</h2><div class="sp"></div><button class="btn-sm" id="importQ">Import JSON</button><button class="btn" id="newQ">Add question</button></div><p class="hint">Review order: content holds first, then missing lesson or skill, then independent math review. Within each priority, questions used by more published exams come first. A release check is separate from independently solving a question. Original questions, diagrams and tables open on demand.</p><div class="control-bar"><div class="field"><label for="bankScope">Data</label><select id="bankScope"><option value="questions">Question bank</option>${track==='est'?'<option value="source">PDF source archive</option>':''}</select></div><div class="field search"><label for="qSearch">Search</label><input id="qSearch" maxlength="200" placeholder="Stable ID, source code, lesson, skill or question"></div><div class="field"><label for="bankStatus">Review filter</label><select id="bankStatus"><option value="">All questions</option><option value="review">Held / needs content review</option><option value="unclassified">Missing lesson or detailed skill</option><option value="pending">No release check recorded</option><option value="source_checked">Release checked · math pending</option><option value="independently_solved">Independently solved</option><option value="ready">Structurally eligible</option></select></div><div class="field"><label for="bankLesson">Lesson</label><select id="bankLesson"><option value="">All lessons</option></select></div><div class="field"><label for="bankSort">Sort by</label><select id="bankSort"><option value="priority">Review priority</option><option value="topic">Lesson A–Z</option><option value="code">Source code</option><option value="type">Answer type</option><option value="difficulty">Recorded difficulty</option></select></div><button class="btn" id="examFromBank" disabled>Create exam from selected</button></div><p id="bankSummary" class="hint"></p><p id="bankCount" class="hint" aria-live="polite"></p><div id="bankError" role="alert"></div><div id="bankTable"></div><div class="actions" style="margin-top:16px"><button class="btn-sm" id="bankPrev">Previous</button><span id="bankPage" class="hint"></span><button class="btn-sm" id="bankNext">Next</button><button class="btn-sm" id="bankClear">Clear selection</button></div>`;
 const container=$('bankTable');
 const current=()=>ST.view==='bank'&&ST.track===track&&container.isConnected;
 const refreshSelected=()=>{const b=$('examFromBank');b.disabled=!chosen.size;b.textContent=chosen.size?`Create exam (${chosen.size})`:'Create exam from selected';};
 const load=async()=>{
  if(!current())return;
  const token=++request;$('bankCount').textContent='Loading question metadata…';$('bankError').innerHTML='';$('bankPrev').disabled=true;$('bankNext').disabled=true;
  // Remove obsolete rows immediately, so they cannot be selected under a new filter.
  container.innerHTML='';
  try{
   const {data,error}=await sb.rpc('admin_bank_page',{p_track:track,p_scope:val('bankScope'),p_search:val('qSearch'),p_lesson:val('bankLesson'),p_status:val('bankStatus'),p_sort:val('bankSort'),p_page:page,p_size:50});
   if(!current()||token!==request)return;if(error)throw error;
   const pages=Math.max(1,Math.ceil(data.total/data.size));if(page>=pages){page=pages-1;return load();}
   const lesson=val('bankLesson');$('bankLesson').innerHTML='<option value="">All lessons</option>'+data.lessons.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('bankLesson').value=lesson;
   $('bankSummary').textContent=`${data.summary.total} entries · ${data.summary.held} need content review · ${data.summary.unclassified} missing lesson or skill · ${data.summary.independently_solved} independently solved`;
   $('bankCount').textContent=data.total?`${page*data.size+1}–${Math.min((page+1)*data.size,data.total)} of ${data.total} matches`:'No questions match these filters.';
   $('bankPage').textContent=`Page ${page+1} of ${pages}`;$('bankPrev').disabled=page===0;$('bankNext').disabled=page+1>=pages;
   container.innerHTML=data.items.length?wrapTable(`<table><thead><tr><th>Select</th><th>Code / stable ID</th><th>Lesson / skill</th><th>Question / source</th><th>Review evidence</th><th>Actions</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${x.ready?`<input type="checkbox" data-bank-select="${x.question_id}" aria-label="Select ${esc(x.code)}" ${chosen.has(x.question_id)?'checked':''}>`:''}</td><td><b>${esc(x.code)}</b>${x.question_id?`<details><summary>Stable ID</summary><small>${esc(x.question_id)}</small></details>`:''}<div class="hint">Priority ${x.priority} · ${x.published_uses} published exams</div></td><td>${esc(x.topic||'Needs lesson classification')}<p class="hint">${esc(x.skill||'Detailed skill needs review')}</p></td><td>${esc(x.stem)}<p class="hint">${esc(x.source)}${x.source_page?' · page '+x.source_page:''}</p>${x.duplicate_of?`<p class="hint">Duplicate of ${esc(x.duplicate_of)}</p>`:''}</td><td><span class="pill ${x.ready?'ok':'warn'}">${esc(BANK_REVIEW_LABELS[x.review_status]||x.review_status)}</span><p class="hint">${esc(x.hold_reason||x.verified_release||'No independent review evidence recorded')}</p><small>${esc(x.type)} · ${esc(x.difficulty)} (recorded)</small></td><td>${val('bankScope')==='source'?`<button class="btn-sm" data-source-id="${esc(x.entry_id)}">View source</button>`:''}${x.question_id?` <button class="btn-sm" data-bank-preview="${x.question_id}">Preview</button> <button class="btn-sm" data-edit-q="${x.question_id}">Edit</button>`:''}</td></tr>`).join('')}</tbody></table>`):'';
   container.querySelectorAll('[data-bank-select]').forEach(b=>b.onchange=()=>{b.checked?chosen.add(b.dataset.bankSelect):chosen.delete(b.dataset.bankSelect);refreshSelected();});
   container.querySelectorAll('[data-source-id]').forEach(b=>b.onclick=()=>openSourceEntry(b.dataset.sourceId));
   container.querySelectorAll('[data-bank-preview]').forEach(b=>b.onclick=()=>openTeachingExam({title:'Question preview',question_ids:[b.dataset.bankPreview]}));
   container.querySelectorAll('[data-edit-q]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const {data,error}=await sb.from('questions').select('*').eq('id',b.dataset.editQ).eq('track_id',track).single();if(error)throw error;if(current())await editQuestion(data);}catch(e){if(current())$('bankError').textContent=e.message||'Could not load this question.';}finally{b.disabled=false;}});
  }catch(e){if(current()&&token===request){$('bankCount').textContent='';$('bankError').innerHTML=`<p class="msg bad">${esc(e.message||'Could not load question bank.')}</p><button class="btn-sm" id="bankRetry">Retry</button>`;$('bankRetry').onclick=load;}}
 };
 const reset=()=>{clearTimeout(timer);page=0;load();};
 $('qSearch').oninput=()=>{clearTimeout(timer);request++;container.innerHTML='';$('bankPrev').disabled=true;$('bankNext').disabled=true;timer=setTimeout(reset,250);};
 for(const id of ['bankScope','bankStatus','bankSort','bankLesson'])$(id).onchange=reset;
 $('bankPrev').onclick=()=>{page--;load();};$('bankNext').onclick=()=>{page++;load();};
 $('bankClear').onclick=()=>{chosen.clear();refreshSelected();container.querySelectorAll('[data-bank-select]').forEach(b=>b.checked=false);};
 $('newQ').onclick=()=>editQuestion();$('importQ').onclick=importQuestions;$('examFromBank').onclick=()=>editExam({},[...chosen]);
 await load();
}
async function bank(){return pagedQuestionBank();}
